name: deploy

on:
  push:
    branches:
      - main
# Do not attempt concurrent deployments.
concurrency:
  group: ${{ github.workflow }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: cache
        uses: actions/cache@v4
        # Keep uv cache and Python virtual environment
        with:
          key: ${{ hashFiles('.python-version', 'uv.lock') }}
          path: |
            ~/.local/share/uv
            .venv
      - run: |
          # Install uv every time 🤷
          pipx install uv

          # Install dependencies and run "deployment" command!
          uv run --verbose textual diagnose
